#!/usr/bin/env python3
"""Generate immutable Git/build identity data for the packaged Python runtime.

The generated module is embedded in the Flet/Serious Python payload. It never
needs Git on the Android device. The fingerprint covers the application Python
source that must match the checked-out commit; app_config.py is intentionally
excluded because CI may inject the public Google Web Client ID immediately
before packaging.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import tomllib
from datetime import datetime, timezone
from pathlib import Path


EXCLUDED = {"core/build_identity.py", "app_config.py"}
SOURCE_ROOTS = ("main.py", "core", "views")


def run_git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def tracked_python_files(root: Path) -> list[Path]:
    names = run_git(root, "ls-files", "-z", "--", "main.py", "core", "views").split("\0")
    files: list[Path] = []
    for name in names:
        if not name or name in EXCLUDED or not name.endswith(".py"):
            continue
        path = root / name
        if path.is_file():
            files.append(path)
    return sorted(files, key=lambda p: p.relative_to(root).as_posix())


def fingerprint(files: list[Path], root: Path) -> str:
    digest = hashlib.sha256()
    for path in files:
        relative = path.relative_to(root).as_posix()
        payload = path.read_bytes()
        file_hash = hashlib.sha256(payload).hexdigest()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_hash.encode("ascii"))
        digest.update(b"\0")
    return digest.hexdigest()


def project_version(root: Path) -> str:
    with (root / "pyproject.toml").open("rb") as handle:
        data = tomllib.load(handle)
    return str(data["project"]["version"])


def git_status(root: Path) -> list[str]:
    raw = run_git(root, "status", "--porcelain", "-z")
    return [entry for entry in raw.split("\0") if entry]


def render_module(values: dict[str, str]) -> str:
    ordered = (
        ("BUILD_COMMIT", values["commit"]),
        ("BUILD_VERSION", values["version"]),
        ("BUILD_NUMBER", values["build_number"]),
        ("BUILD_TIMESTAMP_UTC", values["timestamp_utc"]),
        ("BUILD_BRANCH", values["branch"]),
        ("PYTHON_BUNDLE_FINGERPRINT", values["python_bundle_fingerprint"]),
        ("PYTHON_RUNTIME", values["python_runtime"]),
        ("FLET_VERSION", values["flet_version"]),
    )
    lines = [
        '"""Generated by scripts/generate_build_identity.py; do not edit by hand."""',
        "from __future__ import annotations",
        "",
    ]
    lines.extend(f'{name} = {value!r}' for name, value in ordered)
    lines.extend(
        [
            "",
            "",
            "def as_dict() -> dict[str, str]:",
            "    return {",
            '        "commit": BUILD_COMMIT,',
            '        "version": BUILD_VERSION,',
            '        "build_number": BUILD_NUMBER,',
            '        "timestamp_utc": BUILD_TIMESTAMP_UTC,',
            '        "branch": BUILD_BRANCH,',
            '        "python_bundle_fingerprint": PYTHON_BUNDLE_FINGERPRINT,',
            '        "python_runtime": PYTHON_RUNTIME,',
            '        "flet_version": FLET_VERSION,',
            "    }",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--python-output", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--python-runtime", default="3.12")
    parser.add_argument("--flet-version", default="0.86.5")
    parser.add_argument("--build-number", default="")
    parser.add_argument("--build-version", default="")
    args = parser.parse_args()

    root = args.root.resolve()
    head = run_git(root, "rev-parse", "HEAD")
    github_sha = __import__("os").environ.get("GITHUB_SHA", "").strip()
    if github_sha and github_sha != head:
        raise SystemExit(
            f"GITHUB_SHA {github_sha} does not match git HEAD {head}; refusing to package a different commit."
        )

    status = git_status(root)
    if status:
        raise SystemExit(
            "Working tree is not clean before build identity generation: "
            + ", ".join(status)
        )

    files = tracked_python_files(root)
    if not files:
        raise SystemExit("No tracked application Python files were found.")
    source_fingerprint = fingerprint(files, root)
    version = args.build_version or project_version(root)
    build_number = args.build_number or __import__("os").environ.get("GITHUB_RUN_NUMBER", "LOCAL")
    branch = __import__("os").environ.get("GITHUB_REF_NAME", "LOCAL")
    timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")

    values = {
        "commit": head,
        "version": version,
        "build_number": str(build_number),
        "timestamp_utc": timestamp,
        "branch": branch,
        "python_bundle_fingerprint": source_fingerprint,
        "python_runtime": args.python_runtime,
        "flet_version": args.flet_version,
    }

    python_output = args.python_output.resolve()
    json_output = args.json_output.resolve()
    python_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    python_output.write_text(render_module(values), encoding="utf-8")
    manifest = {
        **values,
        "fingerprint_algorithm": "sha256(relative-path + NUL + file-sha256 + NUL, sorted)",
        "fingerprint_excludes": sorted(EXCLUDED),
        "source_files": [p.relative_to(root).as_posix() for p in files],
    }
    json_output.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
