#!/usr/bin/env python3
"""Add the ReiAnix Android host to a real Flet Cookiecutter build template.

Flet's ``--template`` option accepts a Cookiecutter repository, not an Android
overlay.  CI clones the official Flet template, then this script places the
overlay beside that template and installs a Cookiecutter post-generation hook.
The hook runs *after* Flet renders the Flutter project and *before* Gradle
builds it, so the Kotlin sources, manifest entries, resources, and dependencies
belong to the Android project that produces the APK.
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path



HOOK = r'''# Generated by ReiAnix: runs in the rendered Flutter project before Gradle.
from __future__ import annotations

import os
import shutil
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ANDROID = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", ANDROID)
root = Path.cwd()
overlay = Path(__REIFLIX_OVERLAY_APP__)
app = root / "android" / "app"
if not app.is_dir():
    raise RuntimeError(f"Rendered Flet project has no Android app module: {app}")

# Kotlin sources are copied into the rendered app module, retaining the package
# used by pyproject.toml (com.reiflix.reiflix_local).
source = overlay / "src" / "main" / "kotlin"
destination = app / "src" / "main" / "kotlin"
shutil.copytree(source, destination, dirs_exist_ok=True)

# Copy native tests with the same overlay so generated Android projects retain
# the exact test contract used by the repository.
for test_root in ("src/test", "src/androidTest"):
    source_test = overlay / test_root
    if source_test.is_dir():
        destination_test = app / test_root
        shutil.copytree(source_test, destination_test, dirs_exist_ok=True)

# Keep the generated Flutter launch resources. ReiAnix adds only its own
# player/host theme resource, avoiding replacement of Flutter's LaunchTheme.
res_source = overlay / "src" / "main" / "res"
res_destination = app / "src" / "main" / "res"
values = res_destination / "values"
values.mkdir(parents=True, exist_ok=True)
shutil.copy2(res_source / "values" / "styles.xml", values / "reiflix_styles.xml")
ids_source = res_source / "values" / "reianix_ids.xml"
if not ids_source.is_file():
    raise RuntimeError(f"Missing ReiAnix resource ID contract: {ids_source}")
shutil.copy2(ids_source, values / "reianix_ids.xml")

# Native PlayerView XML belongs to the rendered Android resource tree. Copy the
# overlay resource subtree instead of relying on the source project existing
# beside the generated Flet module.
layout_source = res_source / "layout"
if layout_source.is_dir():
    shutil.copytree(layout_source, res_destination / "layout", dirs_exist_ok=True)

manifest_path = app / "src" / "main" / "AndroidManifest.xml"
tree = ET.parse(manifest_path)
manifest = tree.getroot()
name = "{" + ANDROID + "}name"

# Package visibility is required before preflighting ACTION_OPEN_DOCUMENT_TREE
# on Android 11+; keep the query in the generated APK as part of the native host
# contract rather than treating resolveActivity() as an unobservable guess.
queries = manifest.find("queries")
if queries is None:
    queries = ET.Element("queries")
    manifest.insert(0, queries)
tree_action = None
for query_intent in queries.findall("intent"):
    for action in query_intent.findall("action"):
        if action.get("{" + ANDROID + "}name") == "android.intent.action.OPEN_DOCUMENT_TREE":
            tree_action = action
            break
    if tree_action is not None:
        break
if tree_action is None:
    query_intent = ET.SubElement(queries, "intent")
    ET.SubElement(query_intent, "action", {name: "android.intent.action.OPEN_DOCUMENT_TREE"})
application = manifest.find("application")
if application is None:
    raise RuntimeError("Rendered Flet AndroidManifest has no application element")

# MediaStore is an optional read-only source alongside SAF. Keep the
# permissions version-scoped so Android 13+ uses granular video access while
# older supported devices retain READ_EXTERNAL_STORAGE.
permission_attr = "{" + ANDROID + "}name"
existing_permissions = {node.get(permission_attr) for node in manifest.findall("uses-permission")}
permission_specs = [
    ("android.permission.READ_EXTERNAL_STORAGE", "32"),
    ("android.permission.READ_MEDIA_VIDEO", None),
    ("android.permission.READ_MEDIA_VISUAL_USER_SELECTED", None),
    ("android.permission.MANAGE_EXTERNAL_STORAGE", None),
]
for permission, max_sdk in permission_specs:
    existing_nodes = [
        node for node in manifest.findall("uses-permission")
        if node.get(permission_attr) == permission
    ]
    if existing_nodes:
        # Keep exactly one declaration for each ReiAnix storage permission.
        # Templates can already contain the permission, and duplicate nodes
        # make the generated contract harder to reason about.
        node = existing_nodes[0]
        for duplicate in existing_nodes[1:]:
            manifest.remove(duplicate)
        if permission == "android.permission.READ_EXTERNAL_STORAGE" and max_sdk is not None:
            node.set("{" + ANDROID + "}maxSdkVersion", max_sdk)
        continue
    attrs = {permission_attr: permission}
    if max_sdk is not None:
        attrs["{" + ANDROID + "}maxSdkVersion"] = max_sdk
    manifest.insert(0, ET.Element("uses-permission", attrs))
feature_name_attr = "{" + ANDROID + "}name"
pip_feature = next(
    (
        node for node in manifest.findall("uses-feature")
        if node.get(feature_name_attr) == "android.software.picture_in_picture"
    ),
    None,
)
if pip_feature is None:
    pip_feature = ET.Element("uses-feature", {
        feature_name_attr: "android.software.picture_in_picture",
        "{" + ANDROID + "}required": "false",
    })
    manifest.insert(0, pip_feature)
else:
    pip_feature.set("{" + ANDROID + "}required", "false")

theme_attr = "{" + ANDROID + "}theme"
launch_attr = "{" + ANDROID + "}launchMode"
document_launch_attr = "{" + ANDROID + "}documentLaunchMode"
config_attr = "{" + ANDROID + "}configChanges"
screen_attr = "{" + ANDROID + "}screenOrientation"
pip_attr = "{" + ANDROID + "}supportsPictureInPicture"
exported_attr = "{" + ANDROID + "}exported"
scheme_attr = "{" + ANDROID + "}scheme"
host_attr = "{" + ANDROID + "}host"

# Use the ReiAnix immersive system-bar host policy. The native player reinforces it
# with its own immersive theme below.
application.set(theme_attr, "@style/ReiAnixTheme")
application.set("{" + ANDROID + "}enableOnBackInvokedCallback", "true")
activities = application.findall("activity")
main = next((activity for activity in activities if activity.get(name) in [".MainActivity", "com.reiflix.reiflix_local.MainActivity"]), None)
if main is None:
    raise RuntimeError("Rendered Flet manifest has no MainActivity to replace")
main.set(name, "com.reiflix.reiflix_local.MainActivity")
main.set(exported_attr, "true")
main.set(launch_attr, "singleTask")
main.set(document_launch_attr, "never")
main.set(config_attr, "orientation|screenSize|keyboardHidden")

# Reiflix bridge deep-link retained alongside Flet's launcher intent filter.
bridge = None
for candidate in main.findall("intent-filter"):
    data_nodes = candidate.findall("data")
    if any(
        node.get(scheme_attr) == "reiflix" and node.get(host_attr) == "native"
        for node in data_nodes
    ):
        bridge = candidate
        break
if bridge is None:
    bridge = ET.SubElement(main, "intent-filter")
    ET.SubElement(bridge, "action", {name: "android.intent.action.VIEW"})
    ET.SubElement(bridge, "category", {name: "android.intent.category.DEFAULT"})
    ET.SubElement(bridge, "category", {name: "android.intent.category.BROWSABLE"})
    ET.SubElement(bridge, "data", {scheme_attr: "reiflix", host_attr: "native"})

player_name = "com.reiflix.reiflix_local.NativePlayerActivity"
player = next((activity for activity in application.findall("activity") if activity.get(name) == player_name), None)
if player is None:
    player = ET.SubElement(application, "activity", {
        name: player_name,
        theme_attr: "@style/ReiAnixPlayerTheme",
        launch_attr: "singleTop",
        config_attr: "orientation|screenSize|keyboardHidden",
        screen_attr: "fullSensor",
        pip_attr: "true",
        exported_attr: "false",
    })
else:
    # A template may already declare the player. Keep it non-exported and
    # PiP-capable rather than silently retaining stale manifest attributes.
    player.set(theme_attr, "@style/ReiAnixPlayerTheme")
    player.set(launch_attr, "singleTop")
    player.set(config_attr, "orientation|screenSize|keyboardHidden")
    player.set(screen_attr, "fullSensor")
    player.set(pip_attr, "true")
    player.set(exported_attr, "false")
tree.write(manifest_path, encoding="utf-8", xml_declaration=True)

dependencies = [
    "androidx.activity:activity-ktx:1.13.0",
    "io.coil-kt:coil-compose:2.7.0",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0",
    "androidx.documentfile:documentfile:1.0.1",
    "androidx.media3:media3-exoplayer:1.11.1",
    "androidx.media3:media3-ui:1.11.1",
    "androidx.credentials:credentials:1.6.0",
    "androidx.credentials:credentials-play-services-auth:1.6.0",
    "com.google.android.libraries.identity.googleid:googleid:1.2.0",
]
# Android API 36 requires AGP 8.9.1 or newer. Flet 0.86.5's template may still
# carry an older plugin/wrapper, so upgrade only generated build metadata.
android_root = root / "android"
for candidate in (android_root / "settings.gradle.kts", android_root / "settings.gradle", android_root / "build.gradle.kts", android_root / "build.gradle"):
    if candidate.is_file():
        source = candidate.read_text(encoding="utf-8")
        updated = source.replace("com.android.tools.build:gradle:8.6.1", "com.android.tools.build:gradle:8.9.1")
        # Settings-style plugin declarations normally contain the version as a
        # literal after the plugin id; limit this replacement to the AGP id.
        updated = re.sub(r"(id\s*[\"\']com\.android\.application[\"\']\s+version\s+[\"\'])8\.6\.1([\"\'])",
                         r"\g<1>8.9.1\g<2>", updated)
        if updated != source:
            candidate.write_text(updated, encoding="utf-8")


wrapper = android_root / "gradle" / "wrapper" / "gradle-wrapper.properties"
if wrapper.is_file():
    source = wrapper.read_text(encoding="utf-8")
    updated = re.sub(r'gradle-8\.7(?:\.\d+)?-(bin|all)\.zip', r'gradle-8.11.1-\1.zip', source)
    if updated != source:
        wrapper.write_text(updated, encoding="utf-8")

gradle = next((app / candidate for candidate in ("build.gradle.kts", "build.gradle") if (app / candidate).is_file()), None)
if gradle is None:
    raise RuntimeError("Rendered Flet app module has no Gradle build file")
original = gradle.read_text(encoding="utf-8")
existing = original

# Keep the Android resource namespace aligned with the native package so Kotlin
# resolves the generated R class for copied ReiAnix player resources.
if gradle.suffix == ".kts":
    if re.search(r'namespace\s*=\s*["\'][^"\']+["\']', existing):
        existing = re.sub(
            r'namespace\s*=\s*["\'][^"\']+["\']',
            'namespace = "com.reiflix.reiflix_local"',
            existing,
            count=1,
        )
    else:
        existing = existing.replace(
            "android {",
            'android {\n    namespace = "com.reiflix.reiflix_local"',
            1,
        )
else:
    if re.search(r'namespace\s+["\'][^"\']+["\']', existing):
        existing = re.sub(
            r'namespace\s+["\'][^"\']+["\']',
            "namespace 'com.reiflix.reiflix_local'",
            existing,
            count=1,
        )
    else:
        existing = existing.replace(
            "android {",
            "android {\n    namespace 'com.reiflix.reiflix_local'",
            1,
        )

# Flet resolves targetSdk from pyproject.toml. Keep compileSdk explicit because
# Android 16 APIs require SDK 36 even when Flutter's bundled default lags behind.
existing = existing.replace("compileSdk = flutter.compileSdkVersion", "compileSdk = 36")
existing = existing.replace("compileSdk = 35", "compileSdk = 36")
if "// ReiAnix native host dependencies" not in existing:
    if gradle.suffix == ".kts":
        block = "\n// ReiAnix native host dependencies\ndependencies {\n" + "".join(f'    implementation("{item}")\n' for item in dependencies) + "}\n"
    else:
        block = "\n// ReiAnix native host dependencies\ndependencies {\n" + "".join(f"    implementation '{item}'\n" for item in dependencies) + "}\n"
    gradle.write_text(existing + block, encoding="utf-8")

# The source overlay is not an Android module in the generated Flet project,
# so its build.gradle.kts is not copied. Set this contract in the generated
# module explicitly instead of relying on Flutter template defaults.
existing = gradle.read_text(encoding="utf-8")

# The Compose compiler plugin belongs to the module that applies Kotlin Android.
# Flet's generated root build.gradle.kts is not guaranteed to expose a plugins {}
# DSL block, so never inject a bare plugin declaration into the root script.
compose_plugin_marker = "ReiAnix Compose Compiler Gradle plugin"
if compose_plugin_marker not in existing:
    if gradle.suffix == ".kts":
        plugin_line = '    id("org.jetbrains.kotlin.plugin.compose") version "2.0.21"'
        if "plugins {" in existing:
            existing = existing.replace("plugins {", "plugins {\n" + plugin_line, 1)
    else:
        plugin_line = "    id 'org.jetbrains.kotlin.plugin.compose' version '2.0.21'"
        if "plugins {" in existing:
            existing = existing.replace("plugins {", "plugins {\n" + plugin_line, 1)
    existing += "\n// ReiAnix Compose Compiler Gradle plugin\n"

# PerformanceDiagnostics uses the Android-generated BuildConfig class. Flet's
# rendered Android module does not guarantee BuildConfig generation, so make
# this explicit in the actual Gradle project that will compile the APK.

# Jetpack Compose foundation. earlier validation stage 01 enables the stack but intentionally does
# not attach Compose content to the Flet launcher or migrate an existing screen.
compose_marker = "ReiAnix Jetpack Compose foundation contract"
if compose_marker not in existing:
    if "org.jetbrains.kotlin.plugin.compose" not in existing and "plugins {" in existing:
        if gradle.suffix == ".kts":
            existing = existing.replace(
                "plugins {",
                'plugins {\n    id("org.jetbrains.kotlin.plugin.compose")',
                1,
            )
        else:
            existing = existing.replace(
                "plugins {",
                "plugins {\n    id 'org.jetbrains.kotlin.plugin.compose'",
                1,
            )
    compose_feature_block = """
// ReiAnix Jetpack Compose foundation contract
android {
    buildFeatures {
        compose = true
    }
}
"""
    existing += compose_feature_block

build_config_marker = "ReiAnix BuildConfig generation contract"
if build_config_marker not in existing:
    if gradle.suffix == ".kts":
        build_config_block = """
// ReiAnix BuildConfig generation contract
android {
    buildFeatures {
        buildConfig = true
    }
}
"""
    else:
        build_config_block = """
// ReiAnix BuildConfig generation contract
android {
    buildFeatures {
        buildConfig true
    }
}
"""
    existing += build_config_block
    gradle.write_text(existing, encoding="utf-8")

# Kotlin/JVM and Android instrumentation tests are part of the host contract.

compose_dependency_marker = "ReiAnix Compose dependencies"
if compose_dependency_marker not in existing:
    if gradle.suffix == ".kts":
        compose_block = """
// ReiAnix Compose dependencies
dependencies {
    implementation(platform("androidx.compose:compose-bom:2026.06.00"))
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
    implementation("androidx.navigation:navigation-compose:2.9.8")
    debugImplementation(platform("androidx.compose:compose-bom:2026.06.00"))
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
    androidTestImplementation(platform("androidx.compose:compose-bom:2026.06.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    androidTestImplementation("androidx.compose.ui:ui-test")
    androidTestImplementation("androidx.navigation:navigation-testing:2.9.8")
}
"""
    else:
        compose_block = """
// ReiAnix Compose dependencies
dependencies {
    implementation platform('androidx.compose:compose-bom:2026.06.00')
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-core'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0'
    implementation 'androidx.navigation:navigation-compose:2.9.8'
    debugImplementation platform('androidx.compose:compose-bom:2026.06.00')
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
    androidTestImplementation platform('androidx.compose:compose-bom:2026.06.00')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    androidTestImplementation 'androidx.compose.ui:ui-test'
    androidTestImplementation 'androidx.navigation:navigation-testing:2.9.8'
}
"""
    existing += compose_block

test_dependency_marker = "ReiAnix Kotlin test dependencies"
if test_dependency_marker not in existing:
    if gradle.suffix == ".kts":
        test_block = """
// ReiAnix Kotlin test dependencies
dependencies {
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20260814")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test:core:1.6.1")
    androidTestImplementation("androidx.test.uiautomator:uiautomator:2.3.0")
}
"""
    else:
        test_block = """
// ReiAnix Kotlin test dependencies
dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
}
"""
    existing += test_block
    gradle.write_text(existing, encoding="utf-8")

existing = gradle.read_text(encoding="utf-8")
sdk_marker = "ReiAnix Android 16 SDK contract"
if sdk_marker not in existing:
    if gradle.suffix == ".kts":
        sdk_block = "\n// ReiAnix Android 16 SDK contract\nandroid {\n    compileSdk = 36\n    defaultConfig {\n        targetSdk = 36\n        testInstrumentationRunner = \"androidx.test.runner.AndroidJUnitRunner\"\n    }\n}\n"
    else:
        sdk_block = "\n// ReiAnix Android 16 SDK contract\nandroid {\n    compileSdk 36\n    defaultConfig {\n        targetSdk 36\n        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'\n    }\n}\n"
    gradle.write_text(existing + sdk_block, encoding="utf-8")

# Compress JNI libraries inside the APK itself before signing. This reduces
# the distributable APK size; Android extracts these libraries at install time.
jni_packaging_marker = "ReiAnix compressed native library packaging contract"
if jni_packaging_marker not in existing:
    if gradle.suffix == ".kts":
        jni_packaging_block = """
// ReiAnix compressed native library packaging contract
android {
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
"""
    else:
        jni_packaging_block = """
// ReiAnix compressed native library packaging contract
android {
    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}
"""
    existing += jni_packaging_block
    gradle.write_text(existing, encoding="utf-8")

# The APK workflow executes the existing Kotlin JVM unit tests after the real
# Flet/Gradle Android project has been rendered. This template-preparation step
# itself remains focused on producing the Android host.
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", type=Path, required=True)
    parser.add_argument("--overlay", type=Path, default=Path("android"))
    args = parser.parse_args()
    template = args.template.resolve()
    overlay = args.overlay.resolve()
    if not (template / "cookiecutter.json").is_file():
        parser.error(f"Flet template is not a Cookiecutter repository: {template}")
    source = overlay / "app"
    required = [
        source / "src/main/kotlin/com/reiflix/reiflix_local/MainActivity.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/NativePlayerActivity.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/bridge/NativeMailbox.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/bridge/NativeRequestState.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/bridge/NativeCommandDispatcher.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/bridge/GoogleIdentity.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/NativePlayerRequest.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/DeviceInteractionProfile.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/LocalSubtitleResolver.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/PlayerLocalMetadataStore.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/PlayerMediaPolicy.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/player/SystemUiController.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/ui/player/ReiAnixNativePlayerControls.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/BroadStorageScanner.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/MediaStoreScanner.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/SafScanner.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/NativeScanController.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/NativeScanPublisher.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/scanner/MediaStoreRetryScheduler.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/storage/NativeBatch.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/storage/NativeIndex.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/storage/StorageAuthorization.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/storage/VideoThumbnailExtractor.kt",
        source / "src/main/res/values/styles.xml",
        source / "src/main/res/layout/native_player_view.xml",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        parser.error("Android host overlay is incomplete: " + ", ".join(missing))

    target = template / "reiflix_android_overlay"
    shutil.rmtree(target, ignore_errors=True)
    shutil.copytree(source, target / "app")
    hooks = template / "hooks"
    hooks.mkdir(exist_ok=True)
    hook = hooks / "post_gen_project.py"
    if hook.exists():
        previous = hook.read_text(encoding="utf-8")
        if "# Generated by ReiAnix" in previous:
            content = HOOK
        else:
            content = previous + "\n\n" + HOOK
    else:
        content = HOOK

    # Cookiecutter renders hooks into a temporary file before executing them.
    # Therefore __file__ cannot be used to locate files beside hooks/.
    # Bake the absolute overlay path into the generated hook while preparing
    # the template, so the hook remains valid when Cookiecutter executes it.
    overlay_app = (target / "app").resolve()
    content = content.replace("__REIFLIX_OVERLAY_APP__", repr(str(overlay_app)))
    hook.write_text(content, encoding="utf-8")
    print(f"Prepared native ReiAnix host in Cookiecutter template: {template}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
